const data = {
  Argentina: '#fbaf17',
  Australia: '#009edb',
  Austria: '#009edb',
  Belgium: '#009edb',
  Brazil: '#fbaf17',
  Canada: '#009edb',
  China: '#fbaf17',
  Czechia: '#009edb',
  Egypt: '#fbaf17',
  Finland: '#009edb',
  France: '#009edb',
  Germany: '#009edb',
  Hungary: '#009edb',
  India: '#fbaf17',
  Indonesia: '#fbaf17',
  'Iran (Islamic Republic of)': '#fbaf17',
  Italy: '#009edb',
  Japan: '#009edb',
  Malaysia: '#fbaf17',
  Morocco: '#fbaf17',
  Mexico: '#fbaf17',
  'Netherlands (Kingdom of the)': '#009edb',
  Poland: '#009edb',
  Portugal: '#009edb',
  Romania: '#009edb',
  'Russian Federation': '#009edb',
  Serbia: '#009edb',
  Slovakia: '#009edb',
  Slovenia: '#009edb',
  'South Africa': '#fbaf17',
  'Korea‚ Republic of': '#009edb',
  Spain: '#009edb',
  Sweden: '#009edb',
  Taiwan: '#009edb',
  Thailand: '#fbaf17',
  Türkiye: '#fbaf17',
  Ukraine: '#009edb',
  'United Kingdom': '#009edb',
  'United States of America': '#009edb',
  Uzbekistan: '#fbaf17',
  Others: '#aea29a',
  Colombia: '#fbaf17',
  Kazakhstan: '#fbaf17'
};

const CountryColour = (country) => (data[country]);
export default CountryColour;
